### ISSUE TITLE
Why use sleep? 

### ISSUE THREAD

**Issue by instalator** [Grayda/node-orvibo#13]
Why use sleep? Perhaps you do without this module in the code?

**Comment by Grayda** [comment]
Sleep is used when setting up new sockets. You have to pause a certain amount of time to let the socket you're setting up receive and process the packet. The `sleep` module was the fastest, laziest,  and easiest way to pause the code for long enough to let the packets be processed.

I'm happy to approve a pull request if you'd like to replace the `sleep` dependency with a similar blocking function, or you can comment out the setup functions (including the line to `require('sleep')`), remove the dependency from package.json, then `npm install` again.

I'd remove it myself, but I'm knee-deep in `node-orvibo2`, which will "replace" this library and support far more products than ever before.

**Comment by instalator** [comment]
When will release node-orvibo2? Maybe better then wait for him.

**Comment by Grayda** [comment]
It's still a work in progress. node-orvibo will be your best bet for now, as node-orvibo2 requires me to learn and implement all the new devices and protocols, which may take a bit, as there's a lot more going on here.

If you're interested in keeping up with the code, check it out here: http://github.com/grayda/node-orvibo2

**Comment by instalator** [comment]
Thank you, I'll follow!
