### ISSUE TITLE
Homebridge support?

### ISSUE THREAD

**Issue by BonRm** [Grayda/node-orvibo#14]
Hi, will be possible to use as a homebridge plugin to control Ir device with Allone?
I'm currently using this plugin https://github.com/macnow/homebridge-platform-orvibo but is not supporting Allone

**Comment by Grayda** [comment]
Hi, this is something that you'll need to take up with the author of the homebridge plugin, as node-orvibo has supported the AllOne for quite a while, but @macnow's homebridge plugin doesn't have the code to use the AllOne features.
