### ISSUE TITLE
Constant disconnection

### ISSUE THREAD

**Issue by Iktwo** [Grayda/node-orvibo#6]
I am having some issues trying to control a S20 device. After subscribing to it if I do setState it will fail after sometime, do you have any ideas? Is there any connection I need to keep alive? 

Thanks for this nice module!

**Comment by Grayda** [comment]
Devices loose their subscription after 5 minutes or so, so you'll just need to set a timer to resubscribe to your devices. It's rather simple to do, just add something like this into your code:

```
// After 2 minutes, resubscribe to all found devices.
// If you wish to resubscribe to just one device, pass the object to subscribe
setInterval(function() {
    o.subscribe()
}, 120000)
```

(where `o` is the Orvibo variable, of course)

There is a command you can call (which the Orvibo apps call `heartbeet` [sic]), but I don't think my code has support for that yet, and isn't really important, as the subscribe() function does the same thing as the heartbeat command.

Let me know how you go after setting the interval. If I don't hear anything within two weeks, I'll close off this issue :)

**Comment by Iktwo** [comment]
Thanks! I was wondering if I needed to do something like that!
