### ISSUE TITLE
cant save node 

### ISSUE THREAD

**Issue by malosaa** [Grayda/node-orvibo#8]
npm install --save node-orvibo
npm WARN install Refusing to install node-orvibo as a dependency of itself

regards

**Comment by Grayda** [comment]
Hi malosaa, I'm unable to replicate this on my two development laptops (Mac and Ubuntu) and my desktop (Windows 10).

Here's a few things to try:
- Are you trying to run (or have you accidentally run) `npm install --save node-orvibo` in the `node_modules/node-orvibo` folder?
- Check your package.json file to see if node-orvibo is listed twice
- Check the package.json file in `node_modules/node-orvibo` and see if `node-orvibo` is listed in there (it shouldn't be)
- Completely delete your `node_modules` folder and try running `npm install` again (assuming you've `--save`d packages into your `packages.json` file

Let me know how you go :)

**Comment by malosaa** [comment]
I deleted the node_modules , still the same Error .
I did run iT in the main folder..

I use Windows 7 x64 ultimate

Regards and thanks for quick reply

**Comment by malosaa** [comment]
With npm install i get this 

Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Users\Home Security System\Desktop\lati\node_modules\sleep\build\node_sleep.
vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.pr
ops" was not found. Confirm that the path in the <Import> declaration is correc
t, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files
(x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "reb
uild"
gyp ERR! cwd C:\Users\Home Security System\Desktop\lati\node_modules\sleep
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x8
6)\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! sleep@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@3.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Home Security System\Desktop\lati\npm-debug.log

C:\Users\Home Security System\Desktop\lati>

**Comment by Grayda** [comment]
Looks like your system isn't set up to build packages correctly. I think you might need to install the [Visual C++ Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=48145) and possibly the [Windows 7 SDK](https://www.microsoft.com/en-au/download/details.aspx?id=8279).

Anything else from there would probably be related to the set up of your computer. I can help out where I can, but because the issue isn't with node-orvibo, I may not be able to provide much support.

**Comment by malosaa** [comment]
I maybe have a solution can you prebuild iT for me ? 
I have done that with a other nodejs program and iT works normal.

Regards

**Comment by Grayda** [comment]
I'm going to close this due to age and lack of activity.

If anyone is reading this, have a look at my comment here: https://github.com/Grayda/node-orvibo/issues/12#issuecomment-272670214 which provides a link to installation instructions for node-gyp, which should cover everything you need.
